# Generated by Django 5.2.17 on 2026-09-29 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(blank=True, max_length=150)),
                ("action", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=80)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                ("summary", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name_plural": "audit entries",
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("governance", "Accountability & Information Officer"),
                            ("lawful", "Lawful, limited & purposeful processing"),
                            ("openness", "Openness & information quality"),
                            ("security", "Security safeguards & breaches"),
                            ("rights", "Data subject rights"),
                            ("special", "Special information, children & cross-border"),
                            ("marketing", "Direct marketing & automated decisions"),
                            ("paia", "PAIA (access to information)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "why",
                    models.TextField(
                        help_text="Plain-language explanation of the requirement."
                    ),
                ),
                ("how", models.TextField(help_text="Practical steps.")),
                ("legal_ref", models.CharField(blank=True, max_length=200)),
                ("essential", models.BooleanField(default=True)),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL name of the page in this app that helps.",
                        max_length=80,
                    ),
                ),
                ("action_label", models.CharField(blank=True, max_length=80)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Not started"),
                            ("progress", "In progress"),
                            ("done", "Done"),
                            ("na", "Not applicable"),
                        ],
                        default="todo",
                        max_length=10,
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="What did you do, when, and where is the proof? (e.g. 'Signed IO letter 3 Oct 2026, filed in HR drive'). Also explain why if marked Not applicable.",
                        verbose_name="Notes & evidence",
                    ),
                ),
                ("completed_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Registered (legal) name",
                    ),
                ),
                (
                    "trading_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Trading name"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="E.g. 2015/123456/07. Needed to register your Information Officer.",
                        max_length=50,
                        verbose_name="CIPC registration number",
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=120)),
                (
                    "business_description",
                    models.TextField(
                        blank=True,
                        help_text="One or two sentences. Used in your PAIA manual and privacy notices.",
                        verbose_name="What does the business do?",
                    ),
                ),
                ("physical_address", models.TextField(blank=True)),
                ("postal_address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="General email"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "employee_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Number of employees"
                    ),
                ),
                (
                    "head_name",
                    models.CharField(
                        blank=True,
                        help_text="The CEO, managing director, sole owner or equivalent. By law this person is the Information Officer unless they authorise someone else.",
                        max_length=120,
                        verbose_name="Head of the business",
                    ),
                ),
                (
                    "head_title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Head's job title"
                    ),
                ),
                (
                    "io_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Information Officer – name",
                    ),
                ),
                (
                    "io_title",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Information Officer – job title",
                    ),
                ),
                (
                    "io_email",
                    models.EmailField(
                        blank=True,
                        help_text="Tip: use a role address such as privacy@yourdomain.co.za so it survives staff changes.",
                        max_length=254,
                        verbose_name="Information Officer – email",
                    ),
                ),
                (
                    "io_phone",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="Information Officer – phone",
                    ),
                ),
                (
                    "io_registered",
                    models.BooleanField(
                        default=False,
                        verbose_name="Information Officer registered with the Information Regulator",
                    ),
                ),
                (
                    "io_registration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date registered"
                    ),
                ),
                (
                    "io_registration_reference",
                    models.CharField(
                        blank=True,
                        help_text="The reference/number shown on the eServices portal after registration.",
                        max_length=80,
                        verbose_name="Registration reference",
                    ),
                ),
                (
                    "deputy_io_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Deputy Information Officer – name",
                    ),
                ),
                (
                    "deputy_io_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Deputy Information Officer – email",
                    ),
                ),
            ],
            options={
                "verbose_name": "company profile",
            },
        ),
        migrations.CreateModel(
            name="ComplianceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("details", models.TextField(blank=True)),
                ("due_date", models.DateField()),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "Once-off"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("done_on", models.DateField(blank=True, null=True)),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Related page in this app",
                    ),
                ),
            ],
            options={
                "ordering": ["done_on", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            (
                                "access",
                                "Access to personal information / records (POPIA s23, PAIA s50)",
                            ),
                            ("correction", "Correction of information (s24 – Form 2)"),
                            (
                                "deletion",
                                "Deletion / destruction of information (s24 – Form 2)",
                            ),
                            ("objection", "Objection to processing (s11(3) – Form 1)"),
                            ("marketing", "Stop direct marketing (s69)"),
                            ("complaint", "Privacy complaint"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Type of request",
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(max_length=200, verbose_name="Requester"),
                ),
                (
                    "requester_contact",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Contact details"
                    ),
                ),
                (
                    "received_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        help_text="Email, phone, WhatsApp, letter, in person... (all are valid since the 2025 regulation amendments).",
                        max_length=80,
                        verbose_name="Received via",
                    ),
                ),
                (
                    "identity_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Confirm who they are before releasing or changing information (s23(1)).",
                        verbose_name="Identity verified",
                    ),
                ),
                ("details", models.TextField(verbose_name="What are they asking for?")),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank to calculate automatically (30 days).",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Received"),
                            ("in_progress", "In progress"),
                            ("extended", "Extended (+30 days, requester notified)"),
                            ("completed", "Completed"),
                            ("refused", "Refused"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("granted_full", "Granted in full"),
                            ("granted_partial", "Granted in part"),
                            ("refused", "Refused"),
                            ("no_records", "No records exist"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "refusal_grounds",
                    models.CharField(
                        blank=True,
                        help_text="Only the grounds in PAIA Part 3 Chapter 4 (e.g. s63–s69) may be used.",
                        max_length=250,
                        verbose_name="Grounds for refusal (if any)",
                    ),
                ),
                ("completed_on", models.DateField(blank=True, null=True)),
                (
                    "response_notes",
                    models.TextField(
                        blank=True, verbose_name="What was done / response sent"
                    ),
                ),
            ],
            options={
                "ordering": ["-received_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Short title")),
                (
                    "discovered_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="When was it discovered?",
                    ),
                ),
                (
                    "occurred_on",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="When did it happen (if known)?",
                    ),
                ),
                ("reported_by", models.CharField(blank=True, max_length=120)),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("device", "Lost or stolen laptop / phone / USB"),
                            ("phishing", "Phishing or hacked email/account"),
                            ("ransomware", "Ransomware or malware"),
                            ("misdirected", "Information sent to the wrong person"),
                            ("insider", "Unauthorised access by staff"),
                            ("operator", "Breach at a service provider"),
                            ("paper", "Lost or exposed paper records"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(verbose_name="What happened?")),
                (
                    "personal_info_affected",
                    models.TextField(
                        blank=True,
                        verbose_name="Which personal information was involved?",
                    ),
                ),
                (
                    "people_affected",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Approx. number of people affected",
                    ),
                ),
                (
                    "containment",
                    models.TextField(
                        blank=True,
                        help_text="E.g. reset passwords, remote-wiped device, asked recipient to delete email, contacted IT support.",
                        verbose_name="What have you done to contain it?",
                    ),
                ),
                (
                    "notifiable",
                    models.CharField(
                        choices=[
                            (
                                "yes",
                                "Yes – reasonable grounds to believe it was accessed or acquired",
                            ),
                            (
                                "no",
                                "No – e.g. device was encrypted, or data was recovered unread",
                            ),
                            ("unsure", "Not sure yet – still investigating"),
                        ],
                        default="unsure",
                        help_text="POPIA has no 'low risk' exemption: if the answer is yes, you must notify the Regulator AND the affected people (s22).",
                        max_length=10,
                        verbose_name="Was personal information (probably) accessed or acquired by someone unauthorised?",
                    ),
                ),
                (
                    "regulator_notified_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Regulator notified on"
                    ),
                ),
                (
                    "regulator_reference",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Regulator reference (from the eServices portal)",
                    ),
                ),
                (
                    "subjects_notified_on",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Affected people notified on",
                    ),
                ),
                (
                    "subjects_notification_method",
                    models.CharField(
                        blank=True,
                        help_text="Email, letter to last known address, website notice, news media, or as the Regulator directs (s22(4)).",
                        max_length=200,
                        verbose_name="How were they notified?",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open – investigating"),
                            ("contained", "Contained"),
                            ("notified", "Notifications sent"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "lessons_learned",
                    models.TextField(
                        blank=True, verbose_name="Root cause & lessons learned"
                    ),
                ),
                ("closed_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-discovered_on"],
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft – needs your review"),
                            ("confirmed", "Confirmed accurate"),
                        ],
                        default="confirmed",
                        help_text="Examples added by the app start as drafts. Change to 'Confirmed' once you've checked every field.",
                        max_length=12,
                        verbose_name="Review status",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Supplier / service provider"
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        help_text="E.g. 'Payroll software', 'Email & file storage', 'IT support'.",
                        max_length=250,
                        verbose_name="What they do for you",
                    ),
                ),
                (
                    "personal_info",
                    models.TextField(
                        blank=True,
                        help_text="E.g. 'Employee names, ID numbers, salaries, bank details'.",
                        verbose_name="Personal information they handle",
                    ),
                ),
                (
                    "data_location",
                    models.CharField(
                        blank=True,
                        help_text="Country/region of the servers. Check the provider's website or contract (search '<provider> data residency').",
                        max_length=200,
                        verbose_name="Where is the information stored?",
                    ),
                ),
                (
                    "outside_sa",
                    models.BooleanField(
                        default=False,
                        verbose_name="Stored or accessed outside South Africa",
                    ),
                ),
                (
                    "transfer_basis",
                    models.CharField(
                        choices=[
                            (
                                "local",
                                "Not applicable – information stays in South Africa",
                            ),
                            (
                                "adequate",
                                "Recipient is bound by law/agreement giving adequate protection – s72(1)(a)",
                            ),
                            (
                                "consent",
                                "The people concerned consented to the transfer – s72(1)(b)",
                            ),
                            (
                                "contract",
                                "Necessary for a contract with, or in the interest of, the person – s72(1)(c)/(d)",
                            ),
                            (
                                "benefit",
                                "For the person's benefit and consent impractical – s72(1)(e)",
                            ),
                            ("unknown", "Not yet assessed"),
                        ],
                        default="unknown",
                        help_text="POPIA s72. For EU/UK providers or big cloud providers with data protection terms, 'adequate protection' is usually the right basis.",
                        max_length=12,
                        verbose_name="Legal basis for cross-border transfer",
                    ),
                ),
                (
                    "agreement_in_place",
                    models.BooleanField(
                        default=False,
                        help_text="Can be their standard Data Processing Agreement/Addendum (DPA) or our operator agreement template.",
                        verbose_name="Written agreement with confidentiality & security terms (s21)",
                    ),
                ),
                ("agreement_date", models.DateField(blank=True, null=True)),
                (
                    "agreement_location",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Where is the agreement filed?",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("next_review", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RetentionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_type",
                    models.CharField(max_length=200, verbose_name="Type of record"),
                ),
                ("examples", models.CharField(blank=True, max_length=300)),
                ("period", models.CharField(max_length=120, verbose_name="Keep for")),
                (
                    "starts_from",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Counted from"
                    ),
                ),
                (
                    "legal_source",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Source / reason"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("statutory", "Legal minimum"),
                            ("policy", "Business policy"),
                        ],
                        default="policy",
                        max_length=10,
                    ),
                ),
                (
                    "disposal",
                    models.CharField(
                        blank=True,
                        default="Shred paper; permanently delete electronic copies incl. backups at next rotation",
                        max_length=200,
                        verbose_name="How to destroy",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "ordering": ["order", "record_type"],
            },
        ),
        migrations.CreateModel(
            name="SeedMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("topic", models.CharField(default="POPIA awareness", max_length=200)),
                (
                    "attendees",
                    models.TextField(
                        help_text="Names of everyone who attended (one per line)."
                    ),
                ),
                ("delivered_by", models.CharField(blank=True, max_length=120)),
                (
                    "materials",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Materials / link"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft – needs your review"),
                            ("confirmed", "Confirmed accurate"),
                        ],
                        default="confirmed",
                        help_text="Examples added by the app start as drafts. Change to 'Confirmed' once you've checked every field.",
                        max_length=12,
                        verbose_name="Review status",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g. 'Payroll', 'Recruitment', 'Customer orders & invoicing'.",
                        max_length=200,
                        verbose_name="Activity",
                    ),
                ),
                (
                    "data_subjects",
                    models.CharField(
                        help_text="E.g. employees, job applicants, customer contact persons. Note: companies are also 'data subjects' under POPIA.",
                        max_length=250,
                        verbose_name="Whose information?",
                    ),
                ),
                (
                    "personal_info",
                    models.TextField(
                        help_text="List the categories: name, ID number, bank details, etc.",
                        verbose_name="What information?",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        help_text="Be specific (POPIA s13). This goes into your privacy notices.",
                        verbose_name="Why do you need it?",
                    ),
                ),
                (
                    "lawful_basis",
                    models.CharField(
                        choices=[
                            ("consent", "Consent of the person – s11(1)(a)"),
                            (
                                "contract",
                                "Needed for a contract with the person – s11(1)(b)",
                            ),
                            ("law", "Required by law – s11(1)(c)"),
                            (
                                "subject_interest",
                                "Protects the person's legitimate interest – s11(1)(d)",
                            ),
                            (
                                "legit_interest",
                                "Legitimate interest of the business or a third party – s11(1)(f)",
                            ),
                        ],
                        help_text="Most business processing is 'contract', 'required by law' or 'legitimate interest'. Use consent only when nothing else fits.",
                        max_length=20,
                        verbose_name="Lawful ground (s11)",
                    ),
                ),
                (
                    "lawful_basis_notes",
                    models.CharField(
                        blank=True,
                        help_text="E.g. which law (Income Tax Act, BCEA...).",
                        max_length=250,
                        verbose_name="Lawful ground – notes",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Directly from the person (preferred, s12) or elsewhere?",
                        max_length=250,
                        verbose_name="Where do you get it?",
                    ),
                ),
                (
                    "special_info",
                    models.BooleanField(
                        default=False,
                        help_text="Health, biometrics (fingerprints/face), race, religion, trade union, political views, sex life, or criminal behaviour (s26).",
                        verbose_name="Includes special personal information",
                    ),
                ),
                (
                    "special_info_details",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Special information – details & authorisation",
                    ),
                ),
                (
                    "children_info",
                    models.BooleanField(
                        default=False,
                        help_text="E.g. employees' dependants on medical aid.",
                        verbose_name="Includes information about children (under 18)",
                    ),
                ),
                (
                    "recipients",
                    models.TextField(
                        blank=True,
                        help_text="E.g. SARS, UIF, medical aid, auditors, banks.",
                        verbose_name="Who else receives it?",
                    ),
                ),
                (
                    "cross_border",
                    models.BooleanField(
                        default=False,
                        verbose_name="Sent or stored outside South Africa",
                    ),
                ),
                (
                    "retention",
                    models.CharField(
                        blank=True,
                        help_text="See the Retention schedule for legal minimums.",
                        max_length=250,
                        verbose_name="How long do you keep it?",
                    ),
                ),
                (
                    "security_measures",
                    models.TextField(
                        blank=True,
                        help_text="E.g. password-protected payroll system with 2FA, locked cabinet for paper files.",
                        verbose_name="How is it protected?",
                    ),
                ),
                (
                    "notice_given",
                    models.BooleanField(
                        default=False,
                        verbose_name="People are told about this (privacy notice, s18)",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Responsible person"
                    ),
                ),
                ("last_reviewed", models.DateField(blank=True, null=True)),
                (
                    "operators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="activities",
                        to="compliance.operator",
                        verbose_name="Service providers used",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "processing activities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft – needs your review"),
                            ("confirmed", "Confirmed accurate"),
                        ],
                        default="confirmed",
                        help_text="Examples added by the app start as drafts. Change to 'Confirmed' once you've checked every field.",
                        max_length=12,
                        verbose_name="Review status",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Risk")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="What could go wrong?"),
                ),
                (
                    "likelihood",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 – Very low"),
                            (2, "2 – Low"),
                            (3, "3 – Medium"),
                            (4, "4 – High"),
                            (5, "5 – Very high"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "impact",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 – Very low"),
                            (2, "2 – Low"),
                            (3, "3 – Medium"),
                            (4, "4 – High"),
                            (5, "5 – Very high"),
                        ],
                        default=3,
                        help_text="Harm to the people concerned if it happens.",
                    ),
                ),
                (
                    "mitigation",
                    models.TextField(blank=True, verbose_name="Controls / actions"),
                ),
                ("owner", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("mitigating", "Being addressed"),
                            ("accepted", "Accepted"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="compliance.processingactivity",
                        verbose_name="Related activity",
                    ),
                ),
            ],
            options={
                "ordering": ["-likelihood", "title"],
            },
        ),
    ]
