# Generated by Django 5.2.17 on 2026-09-30 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatorMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('complaint', 'Complaint about us referred by the Regulator (s74–s77)'), ('assessment', 'Assessment of our processing (s89)'), ('information_notice', 'Information notice (s90)'), ('enforcement_notice', 'Enforcement notice (s95)'), ('infringement_notice', 'Infringement notice – administrative fine (s109)'), ('prior_authorisation', 'Prior authorisation notification (s57–s58)'), ('other', 'Other correspondence')], max_length=24, verbose_name='Type')),
                ('received_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Received on')),
                ('regulator_reference', models.CharField(blank=True, max_length=80, verbose_name="Regulator's reference")),
                ('summary', models.TextField(help_text='What the Regulator asks for or alleges, in your own words.', verbose_name='What is it about?')),
                ('response_due', models.DateField(blank=True, help_text="The date in the notice. For an infringement notice, leave blank: it's 30 days after you received it (s109).", null=True, verbose_name='Response or compliance deadline')),
                ('status', models.CharField(choices=[('open', 'Open – action needed'), ('responded', 'Responded / complied'), ('appealed', 'Appealed to the High Court'), ('closed', 'Closed')], default='open', max_length=12)),
                ('responded_on', models.DateField(blank=True, null=True, verbose_name='Responded / complied on')),
                ('actions_taken', models.TextField(blank=True, help_text='Steps taken, information supplied, fine paid, appeal lodged.', verbose_name='What we did')),
                ('documents_location', models.CharField(blank=True, help_text='E.g. a folder path or document system link.', max_length=255, verbose_name='Where the notice and our response are filed')),
            ],
            options={
                'verbose_name': 'Regulator matter',
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='datasubjectrequest',
            name='request_type',
            field=models.CharField(choices=[('access', 'Access to personal information / records (POPIA s23, PAIA s50)'), ('correction', 'Correction of information (s24 – Form 2)'), ('deletion', 'Deletion / destruction of information (s24 – Form 2)'), ('objection', 'Objection to processing (s11(3) – Form 1)'), ('restriction', 'Restriction of processing (s14(6))'), ('consent', 'Withdrawal of consent (s11(2)(b))'), ('marketing', 'Stop direct marketing (s69)'), ('complaint', 'Privacy complaint'), ('other', 'Other')], max_length=20, verbose_name='Type of request'),
        ),
    ]
